site_name: CTIS TAXII Splunk App Documentation
repo_url: https://github.com/splunk/ctis-taxii-splunk-app
nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - User Guide - Curating and Sharing CTI: user-guide.md
  - Troubleshooting: troubleshooting.md
  - Technical Notes: technical-notes.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
