#!/usr/bin/env bash
set -xe

# Standard ucc build
ucc-gen build

# Append custom conf to configuration generated by UCC
output_app_dir="output/TA_CTIS_TAXII"
# Append package/default/restmap.custom.conf to output app's default/restmap.conf
for conf_file_name in "restmap" "web"; do
    output_file="$output_app_dir/default/$conf_file_name.conf"
    input_file="package/default/$conf_file_name.custom.conf"
    echo "Appending $input_file to $output_file"
    echo "" >> "$output_file"
    cat  "$input_file" >> "$output_file"
done

