import styled from "styled-components";
import {variables} from "@splunk/themes";

export const ReadOnlyContainer = styled.div`
    display: flex;
    align-items: center;
    // This padding needs to match the label generated by ControlGroup
    padding: 6px;

    border: 1px solid ${variables.borderColor};
    background-color: ${variables.backgroundColor};
    color: ${variables.contentColorDefault};
    border-radius: 2px;
`;
