import React from "react";
import styled from "styled-components";

export const ReadOnlyContainer = styled.div`
    display: flex;
    align-items: center;
    // This padding needs to match the label generated by ControlGroup
    padding-top: 6px;
    padding-bottom: 6px;
`;
