name: Docker PoC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List
      run: pwd && ls -l
    - name: Install UCC
      run: pip install splunk-add-on-ucc-framework && pip freeze
    
    - name: Docker Hello World
      run: docker run hello-world
      
