name: Package & Release App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
        contents: write # to be able to publish a GitHub release
        issues: write # to be able to comment on released issues
        pull-requests: write # to be able to comment on released pull requests
        id-token: write # to enable use of OIDC for npm provenance
    steps:
    - uses: actions/checkout@v4
    - name: List
      run: pwd && ls -l
    - name: Install UCC
      run: pip install splunk-add-on-ucc-framework && pip freeze
    - name: Build component lib
      run: pwd && cd packages/my-react-component && npm install
    - name: Yarn setup
      run: pwd && yarn setup
    - name: Package App
      run: cd integration_test && ./package.sh
    - name: Upload app artifact
      uses: actions/upload-artifact@v4
      with:
        path: integration_test/ctis.tar.gz
        name: app

  release:
      runs-on: ubuntu-latest
      needs: [package]
      permissions:
          contents: write # to be able to publish a GitHub release
          issues: write # to be able to comment on released issues
          pull-requests: write # to be able to comment on released pull requests
          id-token: write # to enable use of OIDC for npm provenance
      steps:
          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
                node-version: "lts/*"
          - name: Download app artifact
            uses: actions/download-artifact@v4
            with:
                name: app
          - name: Release
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: npx semantic-release

