name: Run Unit Tests (pytest)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List
      run: pwd && ls -l
    - name: Install pytest
      run: pip install pytest
    - name: Run unit tests
      run: pytest TA_CTIS_TAXII/test/

      
