name: Run Unit Tests (pytest)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List
      run: pwd && ls -l
    - name: Install pytest
      run: pip install pytest pytest-cov
    - name: Install requirements
      run: pip install -r TA_CTIS_TAXII/package/lib/requirements.txt
    - name: Run unit tests
      run: python -m pytest -v TA_CTIS_TAXII/test/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      
